# Generated by Django 5.1.1 on 2024-09-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descroption',
            new_name='description',
        ),
    ]
